<?php
if (!defined('BASEPATH')) exit('No direct script access allowed');

/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/11/13 0013
 * Time: 22:15
 */
class Admin_Siteconfig_module extends CI_Module
{
    public function __construct()
    {
        parent::__construct();
        $this->load->model('admin.Siteconfig_model');
    }

    /**
     * 站点设置
     */
    public function index()
    {
        $result = $this->Siteconfig_model->get_config();
        $data['form_post'] = site_url('admin/siteconfig/save');
        $data['row'] = $result;
        $this->load->view('siteconfig/shopconfig', $data);
    }

    /**
     * 站点配置保存
     */
    public function save()
    {
        $data = $this->input->post('Form');
        $result = $this->Siteconfig_model->save($data);
        $returl = site_url('admin/siteconfig/index');
        if ($result) {
            $now_time = date('Y-m-d H:i:s', time());
            $str = <<<PHP
<?php 
if ( ! defined('BASEPATH')) exit('No direct script access allowed');\n\n               
\$config['sitename']        = '{$data['sitename']}';//网站名称
\$config['author']          = '{$data['author']}';//作者
\$config['beian']           = '{$data['beian']}';//备案号
\$config['email']           = '{$data['email']}';//邮箱
\$config['keywords']        = '{$data['keywords']}';//网站关键字
\$config['description']     = '{$data['description']}';//网站描述
\$config['water_type']      = '{$data['water_type']}';//水印类型
\$config['water_text']      = '{$data['water_text']}';//文字水印文字
\$config['water_text_font'] = '{$data['water_text_font']}';//文字水印字体
\$config['water_text_size'] = '{$data['water_text_size']}';//文字水印大小
\$config['water_color']     = '{$data['water_color']}';//文字水印颜色
\$config['water_locate']    = '{$data['water_locate']}';//文字水印位置
\$config['water_pic']       = '{$data['water_pic']}';//图片水印路径
\$config['water_pic_locate'] = '{$data['water_pic_locate']}';//图片水印位置
\$config['water_pic_alpha'] = '{$data['water_pic_alpha']}';//图片水印透明度
\$config['mail_server']     = '{$data['mail_server']}';//邮件服务器
\$config['mail_port']       = '{$data['mail_port']}';//邮件发送端口
\$config['mail_from']       = '{$data['mail_from']}';//发件人地址
\$config['mail_fname']      = '{$data['mail_fname']}';//发件人姓名
\$config['mail_pass']      = '{$data['mail_pass']}';//邮箱密码
\$config['comment_send_email'] = '{$data['comment_send_email']}';//评论是否发送邮件
\$config['email_receive'] = '{$data['email_receive']}';//站长接收评论邮件的邮箱
/* Auto generated by update on {$now_time}*/
PHP;
            file_put_contents(APPPATH . '/config/site_config.php', $str);

            $this->success('操作成功', $returl, true);
        } else {
            $this->error('操作失败', '', true);
        }
    }
}